// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using listly;

#nullable disable

namespace listly.Migrations
{
    [DbContext(typeof(ListlyDbContext))]
    partial class ListlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("listly.Features.Invitation.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("from_uid");

                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("to_uid");

                    b.HasKey("InvitationId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ListId");

                    b.HasIndex("ToUserId");

                    b.ToTable("invitations");
                });

            modelBuilder.Entity("listly.Features.Item.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("CheckedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("checked_by");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("ItemId");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("ListId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("listly.Features.List.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ListId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("icon");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("owner_uid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("ListId");

                    b.HasIndex("OwnerUid");

                    b.ToTable("lists");

                    b.HasData(
                        new
                        {
                            ListId = 1,
                            Description = "Lista para la compra semanal",
                            Icon = "🛒",
                            OwnerUid = "57cV0RNcC9bnCKzbcNiBp1Tzr822",
                            Title = "Lista de Compras"
                        });
                });

            modelBuilder.Entity("listly.Features.List.ListUsers", b =>
                {
                    b.Property<string>("UId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid");

                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.HasKey("UId", "ListId");

                    b.HasIndex("ListId");

                    b.ToTable("list_users");

                    b.HasData(
                        new
                        {
                            UId = "57cV0RNcC9bnCKzbcNiBp1Tzr822",
                            ListId = 1
                        });
                });

            modelBuilder.Entity("listly.Features.Setting.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<bool>("ReceiveInvitationNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceiveItemAddedNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceiveItemDeletedNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceiveItemStatusChangedNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("SettingId");

                    b.HasIndex("UserUid")
                        .IsUnique();

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            ReceiveInvitationNotifications = true,
                            ReceiveItemAddedNotifications = true,
                            ReceiveItemDeletedNotifications = true,
                            ReceiveItemStatusChangedNotifications = true,
                            UserUid = "57cV0RNcC9bnCKzbcNiBp1Tzr822"
                        },
                        new
                        {
                            SettingId = 2,
                            ReceiveInvitationNotifications = true,
                            ReceiveItemAddedNotifications = true,
                            ReceiveItemDeletedNotifications = true,
                            ReceiveItemStatusChangedNotifications = true,
                            UserUid = "hQZnBgjuOwTTGIOVWgGHsE95OOX2"
                        },
                        new
                        {
                            SettingId = 3,
                            ReceiveInvitationNotifications = true,
                            ReceiveItemAddedNotifications = true,
                            ReceiveItemDeletedNotifications = true,
                            ReceiveItemStatusChangedNotifications = true,
                            UserUid = "IMImLkBokLWuwjRGy7Jm7wnBWAB3"
                        });
                });

            modelBuilder.Entity("listly.Features.Subscription.PaymentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("external_reference");

                    b.Property<string>("PreferenceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("preference_id");

                    b.Property<string>("UserUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_uid");

                    b.HasKey("Id");

                    b.ToTable("payment_mappings");
                });

            modelBuilder.Entity("listly.Features.Subscription.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("SubscriptionId");

                    b.ToTable("subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            Description = "Plan gratuito con funciones básicas",
                            Name = "Free",
                            Price = 0.0m
                        },
                        new
                        {
                            SubscriptionId = 2,
                            Description = "Plan premium con todas las funciones",
                            Name = "Premium",
                            Price = 2.00m
                        });
                });

            modelBuilder.Entity("listly.Features.Subscription.UserSubscription", b =>
                {
                    b.Property<string>("UId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("UId", "SubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("user_subscriptions");

                    b.HasData(
                        new
                        {
                            UId = "57cV0RNcC9bnCKzbcNiBp1Tzr822",
                            SubscriptionId = 1,
                            EndDate = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            StartDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            UId = "hQZnBgjuOwTTGIOVWgGHsE95OOX2",
                            SubscriptionId = 1,
                            EndDate = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            StartDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            UId = "IMImLkBokLWuwjRGy7Jm7wnBWAB3",
                            SubscriptionId = 1,
                            EndDate = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            StartDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("listly.Features.User.User", b =>
                {
                    b.Property<string>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FcmToken")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("fcm_token");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.HasKey("UId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UId = "57cV0RNcC9bnCKzbcNiBp1Tzr822",
                            DisplayName = "Federico González",
                            Email = "alambratore@gmail.com",
                            FcmToken = "",
                            PhotoUrl = "https://lh3.googleusercontent.com/a/ACg8ocJPzlf1C9crnRGlPqM8B-86Xm68mJmqQ-2oGr7kW11g4apmgPg=s96-c"
                        },
                        new
                        {
                            UId = "hQZnBgjuOwTTGIOVWgGHsE95OOX2",
                            DisplayName = "Steam Secundario",
                            Email = "steamsecundario@gmail.com",
                            FcmToken = "",
                            PhotoUrl = "https://lh3.googleusercontent.com/a/ACg8ocK35d11bNqi6k1mqlcxakZ7QFmnPHbkbYs4KZ5k47XwxC8YuA=s96-c"
                        },
                        new
                        {
                            UId = "IMImLkBokLWuwjRGy7Jm7wnBWAB3",
                            DisplayName = "Fogón de Hugo",
                            Email = "fogondehugo@gmail.com",
                            FcmToken = "",
                            PhotoUrl = "https://lh3.googleusercontent.com/a/ACg8ocKdkpsOMhRxy-XTt2CyCGKNLs9sQLThXYsv4ZJpQYCWx-qMwg=s96-c"
                        });
                });

            modelBuilder.Entity("listly.Features.Invitation.Invitation", b =>
                {
                    b.HasOne("listly.Features.User.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("listly.Features.List.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("listly.Features.User.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("List");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("listly.Features.Item.Item", b =>
                {
                    b.HasOne("listly.Features.User.User", "CheckedUser")
                        .WithMany()
                        .HasForeignKey("CheckedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("listly.Features.List.List", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedUser");

                    b.Navigation("List");
                });

            modelBuilder.Entity("listly.Features.List.List", b =>
                {
                    b.HasOne("listly.Features.User.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("listly.Features.List.ListUsers", b =>
                {
                    b.HasOne("listly.Features.List.List", "List")
                        .WithMany("ListUsers")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("listly.Features.User.User", "User")
                        .WithMany("ListUsers")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("listly.Features.Setting.Setting", b =>
                {
                    b.HasOne("listly.Features.User.User", "User")
                        .WithOne("Setting")
                        .HasForeignKey("listly.Features.Setting.Setting", "UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("listly.Features.Subscription.UserSubscription", b =>
                {
                    b.HasOne("listly.Features.Subscription.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscription_Subscription");

                    b.HasOne("listly.Features.User.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscription_User");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("listly.Features.List.List", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ListUsers");
                });

            modelBuilder.Entity("listly.Features.Subscription.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("listly.Features.User.User", b =>
                {
                    b.Navigation("ListUsers");

                    b.Navigation("Setting");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
